### ISSUE TITLE
Section order not preserved

### ISSUE THREAD

**Issue by craibuc** [lipkau/PsIni#11]
I would expect the order of INI sections to  match the order of the names in the hash:

    $Category1 = @{“Key1”=”Value1”;”Key2”=”Value2”}
    $Category2 = @{“Key1”=”Value1”;”Key2”=”Value2”}
    $NewINIContent = @{“Category1”=$Category1;”Category2”=$Category2}
    Out-IniFile -InputObject $NewINIContent -FilePath "C:\MyNewFile.ini"

Expected:

    [Category1]
    Key1=Value1
    Key2=Value2

    [Category2]
    Key1=Value1
    Key2=Value2

Actual:

    [Category2]
    Key1=Value1
    Key2=Value2

    [Category1]
    Key1=Value1
    Key2=Value2

**Comment by lipkau** [comment]
fixed with release 1.1.0

**Comment by craibuc** [comment]
Not fixed w/ 1.1.0.

**Comment by lipkau** [comment]
Your example uses normal hashtables.
test with:
      $ini = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
      $ini["Category1"] = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
      $ini["Category1"]["Key1"] = "Value1"
      $ini["Category1"]["Key2"] = "Value2"
      $ini["Category2"] = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
      $ini["Category2"]["Key1"] = "Value1"
      $ini["Category2"]["Key2"] = "Value2"
      $ini | Out-IniFile -FilePath c:\var\test.ini

**Comment by revolter** [comment]
```pwsh
Import-Module PsIni
$Category1 = [ordered]@{"Key1"="Value1";"Key2"="Value2"}
$Category2 = [ordered]@{"Key1"="Value1";"Key2"="Value2"}
$NewINIContent = [ordered]@{"Category1"=$Category1;"Category2"=$Category2}
Out-IniFile -InputObject $NewINIContent -FilePath "C:\settings.ini"
```

should work too ([reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7.1)).
