### ISSUE TITLE
Get-IniContent doesn't work properly with Set-StrictMode -Version Latest

### ISSUE THREAD

**Issue by davidhayesbc** [lipkau/PsIni#19]
I've fixed this in my own code, body needs to be (see below) 

    [CmdletBinding()]
    Param(
        [ValidateNotNullOrEmpty()]
        [ValidateScript({(Test-Path $_)})]
        [Parameter(ValueFromPipeline=$True,Mandatory=$True)]
        [string]$FilePath,
        [char[]]$CommentChar = @(";"),
        [switch]$IgnoreComments
    )

    Begin
    {
        Write-Verbose "$($MyInvocation.MyCommand.Name):: Function started"
        $commentRegex = "^([$($CommentChar -join '')].*)$"
    }

    Process
    {
        Write-Verbose "$($MyInvocation.MyCommand.Name):: Processing file: $Filepath"
        $commentCount =0
        $ini = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
        switch -regex -file $FilePath
        {
            "^\[(.+)\]$" # Section
            {
                $section = $matches[1]
                $ini[$section] = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
                $commentCount = 0
                continue
            }
            $commentRegex # Comment 
            {
                if (!$IgnoreComments)
                {
                    if (!(test-path "variable:section"))
                    {
                        $section = "_"
                        $ini[$section] = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
                    }
                    $value = $matches[1]
                    $commentCount++
                    $name = "Comment" + $commentCount
                    $ini[$section][$name] = $value
                }
                continue
            }  
            "(.+?)\s*=\s*(.*)" # Key
            {
                if (!(test-path "variable:section"))
                {
                    $section = "_" 
                    $ini[$section] = New-Object System.Collections.Specialized.OrderedDictionary([System.StringComparer]::OrdinalIgnoreCase)
                }
                $name,$value = $matches[1..2]
                $ini[$section][$name] = $value
                continue
            }
        }
        Write-Verbose "$($MyInvocation.MyCommand.Name):: Finished Processing file: $FilePath"
        Return $ini
    }

    End
        {Write-Verbose "$($MyInvocation.MyCommand.Name):: Function ended"}
}

**Comment by craibuc** [comment]
Please fork the project, add your code, ensure that the tests pass, then submit a pull request.

**Comment by davidhayesbc** [comment]
Thanks, I'm new to github so I'm still figuring out the process

**Comment by lipkau** [comment]
Hi.

First of, the code you edited is `Get-IniContent`. And **not** `Out-IniFile`.

But I like the idea.
I intend to rename the variables according to PoshCode/PowerShellPracticeAndStyle [#36](https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/36).

@davidhayesbc: If you want to contribute, do as @craibuc  said. You can find some help here: [help.github.com](https://help.github.com/articles/fork-a-repo/)

**Comment by davidhayesbc** [comment]
Whoops, you're right I changed the issue. I was trying to get too many things done on a Friday afternoon
