### ISSUE TITLE
Encoding Windows-1252 not supported

### ISSUE THREAD

**Issue by krusch** [lipkau/PsIni#21]
Some INI files seem to use Windows-1252 encoding (e.g. mdash as x97), which is not a support output encoding.

**Comment by lipkau** [comment]
Thank you for reporting this. I will investigate the issue.

But if this is a limitation of `Add-Content` CmdLet I will not be able to do much about it.

**Comment by craibuc** [comment]
It's fairly easy to change a file's encoding.  See [my answer](http://stackoverflow.com/a/31998545/134367).

**Comment by krusch** [comment]
@craibuc This is about the encoding of files written by PsIni modules, not about the encoding in the Git repository.

**Comment by craibuc** [comment]
Yes, I understand that.  I was simply demonstrating a technique to change a
file's encoding.

**Comment by krusch** [comment]
@craibuc thanks, found the magic line on rereading the post.  Unfortunately Set-Content
relies on Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding, which does not seem to support Windows-1252, valid values are String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, Ascii.

**Comment by lipkau** [comment]
As correctly stated, `Add-Content` is restricts the possible encoding formats to Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding (as state in the [documentation](https://technet.microsoft.com/en-us/library/hh849859.aspx).

This [The Official Scripting Guys Forum! question](https://social.technet.microsoft.com/Forums/scriptcenter/en-US/ac190b87-9415-46f1-8b91-6cd813300e93/powershell-cmdlet-outfile-encoding-problem) addresses this issue.
