### ISSUE TITLE
Support of not well formatted INI files

### ISSUE THREAD

**Issue by lipkau** [lipkau/PsIni#22]
Some INI file's formatting is not optimal.

**Should we support any of these?**
* [ ] extra whitespaces before section
* [ ] extra whitespaces after section
* [x] extra whitespaces around `=`
* [x] different comment char _(supported since 19a413c4f34447595d5e2d27b36316f23681e5f3)_

**Comment by craibuc** [comment]
From a UX perspective, I'd say 'yes' to all 4, but it depends on the level of effort.

**Comment by lipkau** [comment]
The effort is minimal.
The only change necessary for the remaining two point from the OP would be in Get-IniContent line 90:
`"^\s*\[(.+)\]\s*$" # Section`

**Comment by craibuc** [comment]
Might as well.
