### ISSUE TITLE
No Section and Out-IniFile

### ISSUE THREAD

**Issue by gentilvirus** [lipkau/PsIni#23]
In the Get-IniContent, you take care of .ini file with no [Section] of with keys not located in any section

```
if (!($section))  
                {  
                    $section = "No-Section"  
                    $ini[$section] = @{}  
                }  
```

But you don't take care of it in the Out-IniFile.
So if you have an ini file without any section (or with keys that are not in a section), you'll end up with a [No-Section] section, which technically is better but that is certainly not what you want:

Original INI file content

```
Test = OldValue
```

Update the file with something like this:

```
$FileContent = Get-IniContent "c:\ myinifile.ini"
$FileContent["No-Section"]["Test"] = "NewValue"
$FileContent | Out-IniFile "C:\myinifile.ini" –Force
```

Updated INI file content

```
[No-Section]
Test = NewValue
```

**Comment by lipkau** [comment]
Hi.
Thanks for the feedback.

INI files without at least one Section are considered badly-formatted, AFAIK.
Thus, I did not write the functions to support it.

I will do a bit of research and depending on the result, I will add this.
_Wikipedia suggests it's ok not to have Sections: https://en.wikipedia.org/wiki/INI_file#Sections_

**Comment by gentilvirus** [comment]
@lipkau I agree, INI files should have at least one section, however it is not always the case.

And since a workaround to handle INI files with no section was implemented in Get-IniContent, I thought it would make sense to have one in the Out-IniFile as well...

PS: The No-Section comes from an [older version ](https://gallery.technet.microsoft.com/scriptcenter/ea40c1ef-c856-434b-b8fb-ebd7a76e8d91)of your script I see

**Comment by lipkau** [comment]
fexed with 3e7091af58fd9de500acf389f53a1fbcfb0d71b8
