### ISSUE TITLE
If "=" missing from the ini file, it is ignored

### ISSUE THREAD

**Issue by Juvls** [lipkau/PsIni#33]
Hi,

I was trying to use your module to update a nagios conf file, see below an example, and I found out if the "=" is missing (e.g. NRPEListener.dll, CheckWMI.dll)  in the .ini file, it is going to be ignored with get-iniContent

Thanks for your module!

```
[modules]
NRPEListener.dll
NSClientListener.dll
CheckWMI.dll
FileLogger.dll
CheckSystem.dll
CheckDisk.dll
CheckEventLog.dll
CheckHelpers.dll
;# NSCLIENT++ MODULES
;# A list with DLLs to load at startup.
FileLogger.dll
CheckSystem.dll
CheckDisk.dll
NRPEListener.dll
;SysTray.dll
CheckEventLog.dll
CheckHelpers.dll
;CheckWMI.dll
CheckExternalScripts.dll
 
 
;# USE THIS FILE
;  Use the INI file as opposed to the registry if this is 0 and the use_reg in the registry is set to 1
;  the registry will be used instead.
use_file=1
 
[log]
;# LOG DEBUG
;  Set to 1 if you want debug message printed in the log file (debug messages are always printed to stdout when run with -test)
;debug=1
 
;# LOG FILE
;  The file to print log statements to
file=opsview-agent.log
```

**Comment by lipkau** [comment]
What behavior would you expect? An array? Under the Section?

INI files do not support lines without a delimiter.

**Comment by Juvls** [comment]
I would expect to see them under the array/section modules so when I export the .ini file with my change, it does include everything.

Yes it is not very standard for a INI file and I found an alternative to do it, so maybe it's not worth fixing! :)

```
    $iniContent = Get-Content $iniFile |
        %{
            $_ -replace 'string_to_search', 'new_string'
        }
    $iniContent | Out-file $iniFile
```

**Comment by lipkau** [comment]
I am closing this, as I don't see any benefit for the module supporting this use case.
At least for now.
