### ISSUE TITLE
Use [ordered] hashtables

### ISSUE THREAD

**Issue by codespare** [lipkau/PsIni#5]
Although it would bump compatibility requirements to Powershell v3.0, preserving the sections and keys order on round tripping is useful.
This requires a simple modification when initializing the hashtables:
``` $ini= [ordered] @{}```
and
``` $ini[$section] = [ordered] @{}```

**Comment by lipkau** [comment]
I like the idea.
Can you implement this in your fork (please mind https://github.com/lipkau/PsIni/releases/tag/v1.0.4)

I will use v1.0.4 as final version for microsoft script gallery and only update on github.

**Comment by lipkau** [comment]
Hi.
Sorry for the trouble. I should have noticed that the [ordered] attribute is not ps v2 compatible.

I will shortly include the same functionality but in a v2 compatible manner.
see also the comment in the {pull #9](https://github.com/lipkau/PsIni/pull/9)
